name: codestats_flutter
description: View codestats in your phone

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.3.2
  cupertino_icons: ^0.1.2
  date_format: ^1.0.5
  charts_flutter: ^0.5.0
  superpower: ^0.4.0
  flip_box_bar: ^0.2.0
  flutter_circular_chart: ^0.1.0
  fcharts: ^0.0.10
  intl: ^0.15.7
  json_annotation: ^2.0.0
  phoenix_wings: ^0.1.3
  hydrated: ^1.2.1
  dio: ^1.0.13
  flutter_spinkit: ^3.1.0
  rxdart: ^0.20.0
  rflutter_alert: ^1.0.2
  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git
      ref: 8845aceaafc04ccb1db4cc4e7074395cf698c607

dev_dependencies:
  json_serializable: ^2.0.1
  build_runner: ^1.1.2
  flutter_launcher_icons: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/ic_launcher.png

flutter_icons:
  android: true
  image_path: assets/icon/ic_launcher.png