name: codestats_flutter
description: View codestats in your phone

version: 1.0.17+18

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    version: <=1.2.1
  package_info: ^0.3.2
  date_format: ^1.0.5
  charts_flutter:
    path: ../charts/charts_flutter
  superpower: ^0.4.0
  flutter_circular_chart:
    git:
      url: https://github.com/Schwusch/flutter_circular_chart.git
  fcharts: ^0.0.10
  intl: ^0.15.7
  json_annotation: ^2.0.0
  phoenix_wings: ^0.1.3
  dio: ^1.0.13
  flutter_spinkit: ^3.1.0
  rxdart: ^0.20.0
  share: ^0.5.3
  auto_size_text: ^0.3.0
  random_color: ^1.0.3
  path_provider: ^0.4.1
  flutter_inappbrowser:
    git:
      url: git@github.com:pichillilorenzo/flutter_inappbrowser.git
      ref: c34cdf55d52c35a759bf11ffba8fa090980d9744
  flip_panel: ^1.0.0
  bubble_bottom_bar: ^1.0.0
  draggable_scrollbar: ^0.0.4

dev_dependencies:
  json_serializable: ^2.0.1
  build_runner: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/ic_launcher.png

  fonts:
    - family: OCRAEXT
      fonts:
        - asset: fonts/OCRAEXT.TTF
